apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: egressgateway-operator
  namespace: demo-egress
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  profile: empty
  revision: default
  components:
    egressGateways:
    - name: istio-egressgateway
      namespace: demo-egress
      enabled: true
      label:        
        istio: demo-egressgateway
  values:
    gateways:
      istio-egressgateway:
        injectionTemplate: gateway        