apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ingress
  namespace: demo-ingress
spec:
  profile: empty # Do not install CRDs or the control plane
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: demo-ingress
      enabled: true
      label:        
        istio: demo-ingressgateway
      k8s:
        service:
          ports:
            - name: tcp
              protocol: TCP
              port: 9090
            - name: http2
              protocol: TCP
              port: 80
              targetPort: 8080
            - name: https
              protocol: TCP
              port: 443
              targetPort: 8443
            - name: status-port
              protocol: TCP
              port: 15021
              targetPort: 15021
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway