# lack of authorization on Gatway !
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: jwt-require-valid-token
  namespace: demo
spec:
  selector:
    matchLabels:
      app: httpbin    
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]  # requestPrincipals
    to:
    - operation:
        paths: ["/headers"]
  - to:
    - operation:
        ports: ["9000"]
---
# lack of authorization on Gatway !
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tcp-echo-port
  namespace: demo
spec:
  selector:
    matchLabels:
      app: tcp-echo
  action: ALLOW
  rules:  
  - to:
    - operation:
        ports: ["9000"]

