apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: google-apis-gw
  namespace: istio-system
spec:
  selector:
    app: istio-egressgateway
    istio: egressgateway
  servers:
  - port:
      number: 8443 # Container port Number !!!!
      name: tls
      protocol: TLS
    hosts:
    - "*.googleapis.com"
    tls:
      mode: PASSTHROUGH