apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: jwt-istio-testing
  namespace: radoscis
spec:
  selector:
    matchLabels:
      app: httpbin      
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.24/security/tools/jwt/samples/jwks.json"