apiVersion: v1
kind: Service
metadata:
  name: httpbin-ilb-svc
  labels:
    app: httpbin
    service: httpbin
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP  
  selector:
    app: httpbin
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
