apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
    service: tcp-echo
spec:
  type: ClusterIP  
  ports:
  - name: tcp
    port: 9000
    protocol: TCP
  selector:
    app: tcp-echo
---