apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: gatekeeper-system
spec:
  match:
    - excludedNamespaces: ["kube-*", "istio-system"]
      processes: ["*"]
    # Exclude only from audit
    # - excludedNamespaces: ["audit-excluded-ns"]
    #   processes: ["audit"]
    # Exclude from audit, webhook and sync (sync provides metadata information about kluster objects like namespaces)
    # - excludedNamespaces: ["audit-webhook-sync-excluded-ns"]
    #   processes: ["audit", "webhook", "sync"]
    # As gatekeeper can mutate deployed manifests, we can exclude some namespace form mutation only
    # - excludedNamespaces: ["mutation-excluded-ns"]
    #   processes: ["mutation-webhook"]