apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: radoscis
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:  
  - port:
       number: 80
       name: http
       protocol: HTTP
    hosts:
    - "http.test.com"
