apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "http.test.com"
  exportTo:
  - "."
  - "istio-ingress"
  gateways:
  - ingress-gateway
  http:
  - route:
    - destination:
        host: httpbin-ilb-svc
        port:
          number: 80